[package]
name = "yarn-zip"
version = "0.1.0"
edition = "2024"

[dependencies]
deko = "0.4.0"
tar = "0.4.44"
chrono = { version = "0.4.40", default-features = false, features = ["std"] }
axfive-libzip = { git = "https://gitlab.com/yu-re-ka/axfive-libzip" }
dostime = { version = "1.0.0", features = ["chrono-1"] }
